import './App.css'

function App() {
  return (
    <main>
      <nav className="nav shell"><a className="wordmark" href="#top">SA<span>/</span>26</a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="mailto:sugianand89@gmail.com" className="nav-contact">Let's talk <span>-&gt;</span></a></div></nav>
      <section className="hero shell" id="top"><div className="hero-grid"></div><div className="hero-copy reveal"><p className="eyebrow"><span className="status-dot"></span> Available for software + AI roles / 2026</p><h1>I build systems<br /><em>people trust.</em></h1><p className="hero-intro">Computer Science graduate and AI master's student turning complex problems into dependable software, intelligent tools, and better experiences.</p><div className="hero-actions"><a className="button button-bright" href="#work">Explore the work <span>-&gt;</span></a><a className="text-link" href="mailto:sugianand89@gmail.com">Get in touch <span>-&gt;</span></a></div></div><div className="hero-signal reveal delay-one" aria-label="Profile signal visualization"><div className="signal-orbit orbit-one"></div><div className="signal-orbit orbit-two"></div><div className="signal-core"><span>SA</span></div><span className="signal-label label-top">AI / SYSTEMS</span><span className="signal-label label-right">3.97 GPA</span><span className="signal-label label-bottom">DETROIT, MI</span><span className="signal-label label-left">BUILD / DEBUG / SHIP</span></div><div className="hero-index">01 <span>/</span> 04</div></section>
      <section className="metrics shell reveal delay-two"><div><strong>03</strong><span>internships</span></div><div><strong>30+</strong><span>defects resolved</span></div><div><strong>500+</strong><span>devices imaged</span></div><div><strong>3.97</strong><span>GPA</span></div></section>
      <section className="work shell" id="work"><div className="section-heading reveal"><p className="eyebrow">Selected output / 2023 - now</p><h2>Proof over promises.</h2><p className="section-note">A closer look at the systems, products, and people I have helped move forward.</p></div><div className="work-list"><article className="work-card feature-card reveal"><div className="card-topline"><span>01 / EXPERIENCE</span><span>QA + EMBEDDED SYSTEMS</span></div><div className="card-content"><div><p className="card-kicker">Accurate Technologies Inc.</p><h3>Trust is a<br /><em>testable</em> feature.</h3></div><p>Built automated and manual test coverage for automotive diagnostic and ECU interfaces. Found and resolved 30+ defects through root-cause analysis, regression testing, and cross-team debugging.</p></div><div className="card-footer"><span>May - Aug 2025</span><span className="card-arrow">-&gt;</span></div></article><article className="work-card dark-card reveal delay-one"><div className="card-topline"><span>02 / PRODUCT</span><span>BACKEND + FULL STACK</span></div><div className="card-content"><div><p className="card-kicker">NeverEnding</p><h3>Make the<br /><em>invisible</em> work.</h3></div><p>Developed Django and REST systems for financial applications, shipped Java features, and connected React interfaces to secure, efficient data flows.</p></div><div className="card-footer"><span>May - Aug 2024</span><span className="card-arrow">-&gt;</span></div></article><article className="work-card orange-card reveal delay-two"><div className="card-topline"><span>03 / PROJECT</span><span>JAVASCRIPT + GAME DEV</span></div><div className="card-content"><div><p className="card-kicker">The Frantic Run</p><h3>Fast loops.<br /><em>Real feel.</em></h3></div><p>Designed an endless runner with responsive movement, collision detection, scoring, and optimized animation loops for consistent play across devices.</p></div><div className="card-footer"><a href="https://github.com/sugianand/Frantic_Run" target="_blank" rel="noreferrer">GitHub / 2024</a><span className="card-arrow">-&gt;</span></div></article></div></section>
      <section className="about shell" id="about"><div className="about-statement reveal"><p className="eyebrow">The short version</p><h2>Curious enough to ask why.<br /><em>Practical enough to ship.</em></h2><p>I am Suganeshwara, a Wayne State computer scientist with a minor in mathematics and a master's in Artificial Intelligence in progress. I like the hard middle of a problem: the edge cases, the architecture, the moment a rough idea becomes something real.</p><a className="button button-outline" href="mailto:sugianand89@gmail.com">Start a conversation <span>-&gt;</span></a></div><div className="stack reveal delay-one"><p className="eyebrow">Current stack</p><div className="stack-items"><span>Python</span><span>Java</span><span>C++</span><span>TypeScript</span><span>React</span><span>Django</span><span>TensorFlow</span><span>PyTorch</span><span>Docker</span><span>SQL</span><span>Linux</span><span>Git</span></div></div></section>
      <footer className="footer shell"><span>© 2026 Suganeshwara Anand</span><div><a href="https://www.linkedin.com/in/suganeshwara-anand-b86367219/" target="_blank" rel="noreferrer">LinkedIn</a><a href="https://github.com/sugianand" target="_blank" rel="noreferrer">GitHub</a><a href="mailto:sugianand89@gmail.com">Email</a><a href="#top">Back to top ^</a></div></footer>
    </main>
  )
}

export default App
